version: '3.8'
services:
  ramesh-ui-code: # name of app change it 
    image: ramesh-web:appv$BUILD_NUMBER
    build:
      context: . # location of dockerfile 
      dockerfile: Dockerfile # name of dockerfile 
    container_name: ramesh-web-c12 
    ports:
      - 3436:80 # left side port b/w 1024 - 5000  